:fire: remove workaround for ddev node versions

diff --git a/src/templates/ddev/commands/web/wyvr b/src/templates/ddev/commands/web/wyvr
--- a/src/templates/ddev/commands/web/wyvr
+++ b/src/templates/ddev/commands/web/wyvr
@@ -5,22 +5,18 @@
 ## Example: "ddev wyvr" or with additional arguments such as "ddev wyvr dev"
 
 DEBUG=""
-
 for var in "$@"; do
     if [[ "$var" == "--inspect" ]]; then
         DEBUG="--inspect-brk=0.0.0.0"
     fi
 done
-
-NODE=$(find $HOME/.nvm/versions/node/**/bin -name "node" | tail -1)
-
 if [[ -n "$DEBUG" ]]; then
     echo -e "\e[32mNode.js debugging active\e[0m"
 fi
 
+NODE=$(which node)
 if [[ -z "$NODE" ]]; then
-    echo -e "\e[31mNo Node.js found\e[0m"
-    exit 1;
+    echo -e "\e[31mNode.js not found\e[0m"
+    exit 1
 fi
-
 $NODE $DEBUG ./node_modules/\@wyvr/generator/bin/index.js $@
